/*global systemDictionary:true */
/*
+===================== DO NOT MODIFY ======================+
| This file was generated by translate-adapter, please use |
| `translate-adapter adminLanguages2words` to update it.   |
+===================== DO NOT MODIFY ======================+
*/
'use strict';

systemDictionary = {
    Token: {
        en: 'Token',
        de: 'Token',
        ru: 'Токен',
        pt: 'Símbolo',
        nl: 'Token',
        fr: 'Jeton',
        it: 'Gettone',
        es: 'Simbólico',
        pl: 'Znak',
        uk: 'Токен',
        'zh-cn': '代币',
    },
    'Token of application': {
        en: 'Token of application',
        de: 'Token der Application',
        ru: 'Токен приложения',
        pt: 'Token de aplicação',
        nl: 'Token van toepassing',
        fr: 'Jeton de candidature',
        it: 'Token di applicazione',
        es: 'token de aplicación',
        pl: 'Token aplikacji',
        uk: 'Токен програми',
        'zh-cn': '应用令牌',
    },
    Url: {
        en: 'Url',
        de: 'Url',
        ru: 'URL',
        pt: 'url',
        nl: 'Url',
        fr: 'URL',
        it: 'Url',
        es: 'URL',
        pl: 'adres URL',
        uk: 'Url',
        'zh-cn': '网址',
    },
    'Url of Gotify server - http(s): //host(:port)': {
        en: 'Url of Gotify server - http(s): //host(:port)',
        de: 'Url des Gotify server - http(s): //host(:port)',
        ru: 'URL сервера Gotify - http(s): //host(:port)',
        pt: 'URL do servidor Gotify - http(s): //host(:port)',
        nl: 'URL van Gotify-server - http(s): //host(:port)',
        fr: 'URL du serveur Gotify - http(s): //host(:port)',
        it: 'URL del server Gotify - http(s): //host(:port)',
        es: 'Url del servidor Gotify - http(s): //host(:puerto)',
        pl: 'Adres URL serwera Gotify - http(s): //host(:port)',
        uk: 'URL-адреса сервера Gotify - http(s): //host(:port)',
        'zh-cn': 'Gotify 服务器的 URL - http(s): //host(:port)',
    },
    'gotify adapter settings': {
        en: 'Adapter settings for gotify',
        de: 'Adaptereinstellungen für gotify',
        ru: 'Настройки адаптера для gotify',
        pt: 'Configurações do adaptador para gotify',
        nl: 'Adapterinstellingen voor gotify',
        fr: "Paramètres de l'adaptateur pour gotify",
        it: "Impostazioni dell'adattatore per gotify",
        es: 'Configuración del adaptador para gotify',
        pl: 'Ustawienia adaptera dla gotify',
        uk: 'Налаштування адаптера для gotify',
        'zh-cn': 'gotify 的适配器设置',
    },
};
